DROP TABLE IF EXISTS contacts CASCADE;
DROP TABLE IF EXISTS blogs CASCADE;
DROP TABLE IF EXISTS projects CASCADE;

CREATE TABLE contacts (
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  email VARCHAR UNIQUE NOT NULL,
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  password_hash VARCHAR NOT NULL,
  username VARCHAR UNIQUE NOT NULL,
);
CREATE TABLE blogs (
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR,
  content VARCHAR,
);

CREATE TABLE projects (
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
);